title: Tennessee Lunabotics Documentation
description: Documentation for Tennessee Lunabotics robots.
theme: just-the-docs

url: https://docs.tennesseelunabotics.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
